//note:this file is main file

import Head from "next/head";

//components
import Categories from "./categories";
import Footer from "./footer";
import Home from "./home";
import Navbar from "./navbar";
import Stote from "./stote";
import Titr from "./titr";

export default function App() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* for animation library */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
        ></link>
      </Head>

      {/* main of landing page */}
      <Navbar />
      <Home />
      <Titr title="دسته بندی های فروشگاه" />
      <Categories />
      <Titr title="نهال های ما" />
      <Stote />
      <Footer />
    </div>
  );
}
